//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNumberFourFillingTheArrayWithADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnglishWordAndTranslationOfEnglishWordIntoRussian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnglishWordAndTranslationOfEnglishWordIntoRussian()
        {
            this.EnglishWordAndTranslationOfEnglishWordIntoRussianAndCategoriesOfWords = new HashSet<EnglishWordAndTranslationOfEnglishWordIntoRussianAndCategoriesOfWords>();
        }
    
        public int EnglishWordAndTranslationOfEnglishWordIntoRussian1 { get; set; }
        public int idEnglishWord_fk_ { get; set; }
        public int idTranslationOfEnglishWordIntoRussian_fk_ { get; set; }
    
        public virtual EnglishWord EnglishWord { get; set; }
        public virtual TranslationOfEnglishWordIntoRussian TranslationOfEnglishWordIntoRussian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnglishWordAndTranslationOfEnglishWordIntoRussianAndCategoriesOfWords> EnglishWordAndTranslationOfEnglishWordIntoRussianAndCategoriesOfWords { get; set; }
    }
}
