//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNumberFourFillingTheArrayWithADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnglishWord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnglishWord()
        {
            this.EnglishWordAndTranslationOfEnglishWordIntoRussian = new HashSet<EnglishWordAndTranslationOfEnglishWordIntoRussian>();
        }
    
        public int idEnglishWord_pk_ { get; set; }
        public Nullable<int> idPathsToVoiceFilesThatWereCreatedByTheUserEnglishWord_fk_ { get; set; }
        public string Word { get; set; }
    
        public virtual PathsToVoiceFilesThatWereCreatedByTheUser PathsToVoiceFilesThatWereCreatedByTheUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnglishWordAndTranslationOfEnglishWordIntoRussian> EnglishWordAndTranslationOfEnglishWordIntoRussian { get; set; }
    }
}
