//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNumberFourFillingTheArrayWithADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathsToVoiceFilesThatWereCreatedByTheUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PathsToVoiceFilesThatWereCreatedByTheUser()
        {
            this.EnglishWord = new HashSet<EnglishWord>();
        }
    
        public int idPathsToVoiceFilesThatWereCreatedByTheUser_pk_ { get; set; }
        public string Path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnglishWord> EnglishWord { get; set; }
    }
}
